export const projectData = [
  {
    title: "Scalable E-Commerce Backend",
    description: "Microservices based scalable e-commerce backend.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [
      "Built a scalable e-commerce backend with microservices",
      "Ensured reliability, fault tolerance, and efficient deployments",
      "30+ ⭐ Stars on GitHub",
    ],
    technologies: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "Docker",
      "Nginx",
      "Kubernetes",
      "Stripe",
    ],
    href: "https://github.com/Thisisaarush/scalable-ecommerce-backend",
  },
  {
    title: "URL Shortening Service",
    description:
      "A URL shortening service with features including URL shortening, redirection, updating, and deletion, along with caching using Redis and rate limiting for performance optimization.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [
      "Caching using Redis and rate limiting for performance optimization",
    ],
    technologies: [
      "Node.js",
      "Express.js",
      "Redis",
      "Docker",
      "MongoDB",
      "Morgan",
    ],
    href: "https://github.com/Thisisaarush/url-shortening-service",
  },
  {
    title: "Image Processing Service",
    description:
      "The Image upload service allows users to upload, retrive, delete, transform images to/from AWS S3.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [
      "User authentication using JWT",
      "Upload, Retrive, Delete, List images to/from AWS S3",
      "Transform images using Sharp library",
      "Cache transformed images using Redis",
      "Using RabbitMQ for async processing (Transforming images)",
      "Docker and Docker-compose for containerization",
      "Using Kubernetes for deployment",
    ],
    technologies: [
      "Node.js",
      "Express.js",
      "Redis",
      "Docker",
      "MongoDB",
      "RabbitMQ",
      "Sharp",
      "AWS S3",
    ],
    href: "https://github.com/Thisisaarush/Image-Processing-Service",
  },
  {
    title: "Caching Proxy Service",
    description:
      "This is a simple caching proxy service that caches the responses from the server and serves the cached response for the same request in the future.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [
      "Caching: The service caches the responses from the origin server and serves the cached response for the same request in the future.",
      "Cache Expiry: The service supports cache expiry. The cache is invalidated after a certain time period.",
      "Cache Clearing: The service provides an option to clear the cache manually.",
    ],
    technologies: ["Node.js", "Express.js", "Axios", "Commander", "Node-cache"],
    href: "https://github.com/Thisisaarush/caching-proxy-service",
  },
  {
    title: "Worddle Game",
    description:
      "Worddle is a word puzzle game that challenges players to find words in a grid of letters.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [],
    technologies: ["Typescript", "React", "Next.js", "Tailwind CSS"],
    href: "https://worddlegame.vercel.app/",
  },
  {
    title: "Discooord",
    description:
      "A Discord clone with features like real-time messaging, voice and video calls, and server management.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [
      "Real-time messaging, voice and video calls, server management",
      "End-to-end encryption for secure communication",
    ],
    technologies: [
      "Typescript",
      "React",
      "Next.js",
      "Socket.io",
      "Prisma",
      "Zustand",
      "Tailwind CSS",
      "LiveKit",
    ],
    href: "https://github.com/Thisisaarush/Discooord",
  },
  {
    title: "SnipZ",
    description:
      "SnipZ is a platform for developers to share, search, and organize code snippets.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [
      "Code snippet sharing, searching, and organizing",
      "User authentication and authorization",
    ],
    technologies: [
      "Typescript",
      "React",
      "Next.js",
      "Prisma",
      "Tailwind CSS",
      "Cloudinary",
      "Clerk",
      "GitHub API",
    ],
    href: "https://snipz-app.vercel.app/",
  },
  {
    title: "Shoez-Store",
    description:
      " A full-stack e-commerce website with features like product management, user authentication, cart management, and payment gateway integration.",
    role: "Creator & Maintainer",
    period: "",
    achievements: [
      "Product management, user authentication, cart management",
      "RazorPay Payment Gateway Integration",
      "Secure Login and Registration with bcrypt and JWT",
    ],
    technologies: [
      "Typescript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Zustand",
      "GraphQL",
      "Framer",
      "Motion",
      "Prisma",
      "RazorPay",
    ],
    href: "https://shoez-store.vercel.app/",
  },
]
